-- Create a table for public profiles
CREATE TABLE if not exists public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  updated_at timestamp with time zone,
  full_name text,
  email text,
  bio text,
  website_url text,
  linkedin_url text
);

-- Table for pitches
CREATE TABLE if not exists public.pitches (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    entrepreneur_id uuid REFERENCES public.profiles,
    pitch_title text,
    anonymized_summary text,
    full_text text,
    sector text,
    investment_required text,
    estimated_returns text,
    views integer DEFAULT 0,
    CONSTRAINT anonymized_summary_no_contact_info CHECK ((anonymized_summary !~* '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b' AND anonymized_summary !~* '\+?[0-9]{10,15}'))
);

-- Table for pitch files
CREATE TABLE if not exists public.pitch_files (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    pitch_id uuid REFERENCES public.pitches,
    file_path text NOT NULL,
    file_name text,
    watermarked boolean DEFAULT false,
    watermarked_path text,
    quarantined boolean DEFAULT false,
    has_contact_info boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone
);

-- Table for investor subscriptions
CREATE TABLE if not exists public.investor_subscriptions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL UNIQUE,
    stripe_customer_id text,
    stripe_subscription_id text,
    status text,
    current_period_end timestamp with time zone
);

-- Table for financial transactions
CREATE TABLE if not exists public.transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE,
    stripe_charge_id text,
    amount integer,
    currency text,
    status text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table for reports of violations
CREATE TABLE if not exists public.reports (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now() not null,
    report_type text,
    description text,
    related_user_id uuid references auth.users,
    related_pitch_id uuid references public.pitches,
    resolved boolean default false
);
